name: Manual Trigger

on:
  workflow_dispatch:

env:
  SAMPLE_APP_FRONTEND_SERVICE_JAR: "s3://aws-appsignals-sample-app/main-service.jar"
  SAMPLE_APP_REMOTE_SERVICE_JAR: "s3://aws-appsignals-sample-app/remote-service.jar"
  APP_SIGNALS_ADOT_JAR: "https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar"
  METRIC_NAMESPACE: AppSignals
  LOG_GROUP_NAME: /aws/appsignals/generic

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # vaadin 14 tests fail with node 18
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache local Maven repository
        id: cache-local-maven-repo
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/io/opentelemetry/
          key: ${{ runner.os }}-maven-local-${{ hashFiles('.github/patches/opentelemetry-java*.patch') }}

      - name: Publish patched dependencies to maven local
        uses: ./.github/actions/patch-dependencies
        if: steps.cache-local-maven-repo.outputs.cache-hit != 'true'
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_password: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run Command
        run: |
          ./gradlew testing:validator:run --args='--dry-run-compile true'
